post_install() {
    echo -e "\033[34m Remember to run generate_bootimg.sh to generate boot.img.\033[0m"
}

post_upgrade() {
  post_install
  if findmnt --fstab -uno SOURCE /boot &>/dev/null && ! mountpoint -q /boot; then
    echo "WARNING: /boot appears to be a separate partition but is not mounted."
  fi
}

post_remove() {
  rm -f boot/initramfs-linux-uz801.img
  rm -f boot/initramfs-linux-uz801-fallback.img
}
