post_install() {

    echo -e "\n\033[34mYou should install zotero-pdf-translate plugin by yourself if you are using zotero7.\033[0m"
    echo -e "\033[34mThe file is on:\033[0m"
    echo -e "\033[32m /usr/lib/zotero/extensions/zoteropdftranslate@euclpts.com.xpi \033[0m\n"

}

post_upgrade() {
    post_install
}

post_remove() {
    echo -e "\n\033[34mYou should remove zotero-pdf-translate plugin in zotero by yourself if your are using zotero7.\033[0m\n"
}
