post_install() {
  echo -e "\e\033[34m You must install d3dcompiler_47 and d3dx11_43, don't install dxvk. I have do this in this package, if not you can use winetrick to install.\033[0m"
  echo -e "\e\033[34m E5005: Function 'atan2' is not defined, such a error is threw by missing d3dcompiler_47. \033[0m"
  echo -e "\e\033[34mThe game's data is in \$HOME/.local/share/wine-game/\$pkgname\033[0m"
}

post_upgrade() {
    post_install
}

